
CREATE TABLE IF NOT EXISTS PENSION (
	CODPENSION INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDAD VARCHAR (25) NOT NULL);
    
CREATE TABLE IF NOT EXISTS EPS (
	CODEPS INT AUTO_INCREMENT PRIMARY KEY,
    ENTIDAD VARCHAR (25) NOT NULL);
    
CREATE TABLE IF NOT EXISTS DEPENDENCIA (
	CODDEP INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR (50) NOT NULL);
    
CREATE TABLE IF NOT EXISTS CARGO (
	CODCARGO INT AUTO_INCREMENT,
    TIPO VARCHAR (150) NOT NULL,
    CODDEP INT NOT NULL,
    PRIMARY KEY (CODCARGO),
    FOREIGN KEY (CODDEP)
		REFERENCES DEPENDENCIA (CODDEP)
        ON UPDATE RESTRICT ON DELETE CASCADE);
        
CREATE TABLE IF NOT EXISTS EMPLEADO (
	CODEMPLEADO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    SUELDO INT NOT NULL,
    CODCARGO INT NOT NULL,
    CODEPS INT NOT NULL,
    CODPENSION INT NOT NULL,
    PRIMARY KEY (CODEMPLEADO),
    FOREIGN KEY (CODCARGO)
		REFERENCES CARGO (CODCARGO)
        ON UPDATE RESTRICT ON DELETE CASCADE,
	 FOREIGN KEY (CODEPS)
		REFERENCES EPS (CODEPS)
        ON UPDATE RESTRICT ON DELETE CASCADE,
         FOREIGN KEY (CODPENSION)
		REFERENCES PENSION (CODPENSION)
        ON UPDATE RESTRICT ON DELETE CASCADE
        );